/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordToPdfRouteImport } from './routes/word-to-pdf'
import { Route as PdfToWordRouteImport } from './routes/pdf-to-word'
import { Route as MergePdfRouteImport } from './routes/merge-pdf'
import { Route as EditPdfTextRouteImport } from './routes/edit-pdf-text'
import { Route as CompressPdfRouteImport } from './routes/compress-pdf'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'

const WordToPdfRoute = WordToPdfRouteImport.update({
  id: '/word-to-pdf',
  path: '/word-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PdfToWordRoute = PdfToWordRouteImport.update({
  id: '/pdf-to-word',
  path: '/pdf-to-word',
  getParentRoute: () => rootRouteImport,
} as any)
const MergePdfRoute = MergePdfRouteImport.update({
  id: '/merge-pdf',
  path: '/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const EditPdfTextRoute = EditPdfTextRouteImport.update({
  id: '/edit-pdf-text',
  path: '/edit-pdf-text',
  getParentRoute: () => rootRouteImport,
} as any)
const CompressPdfRoute = CompressPdfRouteImport.update({
  id: '/compress-pdf',
  path: '/compress-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/edit-pdf-text': typeof EditPdfTextRoute
  '/merge-pdf': typeof MergePdfRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/word-to-pdf': typeof WordToPdfRoute
  '/tools/$slug': typeof ToolsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/edit-pdf-text': typeof EditPdfTextRoute
  '/merge-pdf': typeof MergePdfRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/word-to-pdf': typeof WordToPdfRoute
  '/tools/$slug': typeof ToolsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compress-pdf': typeof CompressPdfRoute
  '/edit-pdf-text': typeof EditPdfTextRoute
  '/merge-pdf': typeof MergePdfRoute
  '/pdf-to-word': typeof PdfToWordRoute
  '/word-to-pdf': typeof WordToPdfRoute
  '/tools/$slug': typeof ToolsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compress-pdf'
    | '/edit-pdf-text'
    | '/merge-pdf'
    | '/pdf-to-word'
    | '/word-to-pdf'
    | '/tools/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compress-pdf'
    | '/edit-pdf-text'
    | '/merge-pdf'
    | '/pdf-to-word'
    | '/word-to-pdf'
    | '/tools/$slug'
  id:
    | '__root__'
    | '/'
    | '/compress-pdf'
    | '/edit-pdf-text'
    | '/merge-pdf'
    | '/pdf-to-word'
    | '/word-to-pdf'
    | '/tools/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompressPdfRoute: typeof CompressPdfRoute
  EditPdfTextRoute: typeof EditPdfTextRoute
  MergePdfRoute: typeof MergePdfRoute
  PdfToWordRoute: typeof PdfToWordRoute
  WordToPdfRoute: typeof WordToPdfRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/word-to-pdf': {
      id: '/word-to-pdf'
      path: '/word-to-pdf'
      fullPath: '/word-to-pdf'
      preLoaderRoute: typeof WordToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdf-to-word': {
      id: '/pdf-to-word'
      path: '/pdf-to-word'
      fullPath: '/pdf-to-word'
      preLoaderRoute: typeof PdfToWordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merge-pdf': {
      id: '/merge-pdf'
      path: '/merge-pdf'
      fullPath: '/merge-pdf'
      preLoaderRoute: typeof MergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-pdf-text': {
      id: '/edit-pdf-text'
      path: '/edit-pdf-text'
      fullPath: '/edit-pdf-text'
      preLoaderRoute: typeof EditPdfTextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compress-pdf': {
      id: '/compress-pdf'
      path: '/compress-pdf'
      fullPath: '/compress-pdf'
      preLoaderRoute: typeof CompressPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompressPdfRoute: CompressPdfRoute,
  EditPdfTextRoute: EditPdfTextRoute,
  MergePdfRoute: MergePdfRoute,
  PdfToWordRoute: PdfToWordRoute,
  WordToPdfRoute: WordToPdfRoute,
  ToolsSlugRoute: ToolsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
